pull_requests:
  do_not_increment_build_number: true
version: '{build}'
branches:
  only:
  - master
shallow_clone: true
image: Visual Studio 2017
cache:
  - C:\Users\appveyor\.cargo
  - target\
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
build_script:
  - cargo build --verbose --all
  - cargo test --verbose --all
